name: Publish Next
on:
  release:
    types: [ prereleased ]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    uses: ./.github/workflows/publish.yaml
    with:
      npm-tag: next
