name: Publish Latest
on:
  release:
    types: [ released ]

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    uses: ./.github/workflows/publish.yaml
    with:
      npm-tag: latest
